server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/blog/Public;
    index Router.php;

    server_name _;

    location / {
        try_files $uri $uri/ /Router.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_pass unix:/run/php-fpm/www.sock;
    }

    location ~ /\. {
        deny all;
    }
}