# PHP-FPM configuration file for Nginx.
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/blog/Public;

	# Add index.php to the list if you are using PHP.
	index Router.php;

	server_name _;
	location / {
		try_files $uri $uri/ /Router.php?$query_string;
	}

	# Pass PHP scripts to FastCGI server.
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/run/php/php8.5-fpm.sock;
	}

	# Deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one.
	location ~ /\. {
		deny all;
	}
}